// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygvytolgeivoqhtelvuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlndnl0b2xnZWl2b3FodGVsdnV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MjI5NjcsImV4cCI6MjA2OTk5ODk2N30.Pli6qWXUxXL3c3bP6Dc6FR3LOWBdBRec7ToOY-hyp7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});